### ISSUE TITLE
Add ability to search invoices by invoice number

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#11]
(iref 37356)

I believe this is in progress but wanted to make sure it's noted here.

**Comment by grantalltodavid** [comment]
This is coming in v3.7.  See https://github.com/sliced-invoices/sliced-invoices/commit/152be4dd53cd6c3b5605ee396f381ca96bef003f

**Comment by nutsandbolts** [comment]
Solved via https://github.com/sliced-invoices/sliced-invoices/commit/152be4dd53cd6c3b5605ee396f381ca96bef003f
