### ISSUE TITLE
Change client dropdown in edit screen to search box?

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#12]
(iref 36908)

Depending on the number of clients a user has, the "Choose client" dropdown can be a bit awkward to navigate. Could we change this to a search box instead, where the user can begin typing and then select the desired client? Screenshot: https://cloudup.com/cBXOcH5aZYQ

**Comment by grantalltodavid** [comment]
Done, see 664624f2d6015c6cb027937bcb11c34314133959.  Feature will be included in v3.8.0 release.
