### ISSUE TITLE
Prices exclusive vs. inclusive of tax

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#13]
(iref 35563)

This may be in the works already, but just adding it here. This should be a global option with per-quote or per-invoice options to override the global setting.

**Comment by grantalltodavid** [comment]
This will be in v3.7.  See https://github.com/sliced-invoices/sliced-invoices/commit/9d70aea7cef1a5a65afbb382d8950327f49c30ae
