### ISSUE TITLE
Setting decimals to zero for payments also removes decimals from quantity

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#17]
(iref 31149)

If you set "number of decimals" to zero in the payment settings, the quantity also won't accept decimals, so you can no longer charge for 0.5 hours (for example).

**Comment by grantalltodavid** [comment]
Okay, we will no longer format how the quantity number is displayed.  You can enter whatever quantity you want... 5, 5.00, 0.5, 0.50, etc., and it will be displayed as-is.

See https://github.com/sliced-invoices/sliced-invoices/commit/c614c0df74b561c3fd3b623a264db55e5de40f19

**Comment by grantalltodavid** [comment]
Fixed via c614c0d
