### ISSUE TITLE
Add manual "payment received" email option

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#19]
(iref 29819)

Add the ability to trigger payment confirmations when a customer pays via cash or check by manually clicking a link (or perhaps sending automatically and/or having a button available when a payment is added in the edit screen).

**Comment by grantalltodavid** [comment]
This is coming in v3.7.  See https://github.com/sliced-invoices/sliced-invoices/commit/fbafadcb9c30bc7f92470350df39c33175c45a35

**Comment by nutsandbolts** [comment]
Closed via https://github.com/sliced-invoices/sliced-invoices/commit/fbafadcb9c30bc7f92470350df39c33175c45a35
