### ISSUE TITLE
Additional Tax: Compound vs. normal bug

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#21]
(iref 34460)

When the tax type is set to "compound" the calculations are still shown as the "normal" type within the edit screen. The front end view is correct.

**Comment by grantalltodavid** [comment]
This bug was fixed a while ago. Are we sure we are taking about the latest version of the Additional Tax extension?

**Comment by nutsandbolts** [comment]
Maybe not - the ticket was still open so I’ll close this out.
