### ISSUE TITLE
Allow VAT to be calculated in reverse and itemized 

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#26]
(iref 27431)

User requests some changes to the way VAT is calculated and displayed on invoices. This is part of a larger discussion of VAT in general, but wanted to note it here.

**Comment by grantalltodavid** [comment]
The underlying request here seems to be the same as https://github.com/sliced-invoices/sliced-invoices/issues/13, which is being added in v3.7.  Closing this for now, although I'm sure this is not the last time we'll be talking about VAT.
