### ISSUE TITLE
Don't show invoice viewed notification when viewed by admin

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#27]
When an admin views a quote or invoice, the dashboard notification pops up, which can be confusing if you haven't sent to the client yet. Would be better to show this only when a non-admin views it.

Improvement: Consider adding IP address of who viewed and/or user if they're logged in.

Improvement: Allow option to receive the notifications via email, in the dashboard, or both. Personally I'd rather receive them via email and not clutter up my dashboard, especially since each one has to be cleared individually.

Improvement: Show all notifications in one dialog that can be cleared instead of separate ones? Not sure if some people would prefer to deal with them one by one.

**Comment by grantalltodavid** [comment]
I just did a quick check of this in both multisite and regular setups... for me admin views are not logged, as expected.  So there must be some other piece of the puzzle I'm missing here.  Let's keep this open.

**Comment by nutsandbolts** [comment]
I’ll do some more testing on my end this week as well and see what I can find.

**Comment by nutsandbolts** [comment]
This is resolved in 3.7 - still have no idea what was wrong but it's not doing it anymore. Closing this one for now.
