### ISSUE TITLE
Allow invoice slug to be used for invoice PDF filename

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#28]
(iref 39827)

A customer has requested that the custom invoice slug also be used for the PDF filename, and I think this makes sense for both quotes and invoices, especially since people use those fields to translate the words into other languages.

**Comment by grantalltodavid** [comment]
We have a code snippet for this. https://slicedinvoices.com/developers/code-snippets/ under "PDF extension" / "change PDF filenames".
