### ISSUE TITLE
Remove commented line in admin > js > decimal.min.js

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#33]
The line at the bottom of this file `//# sourceMappingURL=doc/decimal.js.map` results in a 500 error in Safari as neither the .map file nor the /doc/ folder are included.

**Comment by nutsandbolts** [comment]
https://github.com/sliced-invoices/sliced-invoices/blob/master/admin/js/decimal.min.js#L3

**Comment by grantalltodavid** [comment]
I would rather not edit files in vendor libraries, even if its just removing one line.  We'll include the .map file instead.  See: https://github.com/sliced-invoices/sliced-invoices/commit/195a3db952b61b0ccc2be931d690772bc1780a01
