### ISSUE TITLE
i18n issues

### ISSUE THREAD

**Issue by reff** [sliced-invoices/sliced-invoices#47]
- Some built-in strings should be added into the language files and used upon SI taxonomy registering. For example, _Add New Invoice/Quote_ aren't translated.
- On the page where the Invoices and Quotes are listed the filter criterias aren't translated as well (_Accepted, Declined, Draft, Expired, Sent_) 
- The creation date on the Invoices and Quotes listing pages isn't translated (e.g. _6 months ago_)

**Comment by reff** [comment]
Pease refer to the [screenshot](https://slicedinvoices.com/?wpas-attachment=56754)

**Comment by reff** [comment]
One more [screenshot](https://slicedinvoices.com/?wpas-attachment=56774)

**Comment by reff** [comment]
And one more [screenshot](https://slicedinvoices.com/?wpas-attachment=56812)

**Comment by reff** [comment]
https://slicedinvoices.com/?wpas-attachment=57190

**Comment by grantalltodavid** [comment]
Fixed, see a9bad7902018eea398cda482910b6782371331d8

Screenshot 1:
-- "Export as CSV" button: I could not reproduce any issue here.  The string is already translatable as a whole string.
-- "Sent X ago": joined separate translatable strings into 1 whole translatable string
-- "Add New Invoice"/"Add New Quote", "Status"/"Statuses", etc: these are now translatable as whole strings.
-- individual invoice/quote status names (like "draft", "unpaid", "paid", etc.) are already translatable but the Easy Translate extension is required for this.  (Or you can do it with your own custom filter... but it's not possible to translate this by .po files.)

Screenshot 2: I could not reproduce this issue.  I tested each possible setting for converting quotes to invoices, and each time I received an email with the correct button text for the type of message.  If the user still has the issue they should open a support ticket, as it must be something specific to their site.

Screenshot 3: The string "Enter your email address and we'll send you a link you can use to pick a new password." is translatable for me, it works correctly in PoEdit.  I noticed the text domain was wrong so I fixed this... it didn't cause an issue for me but maybe in the user's translation software it did.

Screenshot 4: Understood and fixed.  Even though the strings are translatable, having the sentence split into parts meant languages (like German) could not re-assemble the sentence in a different order.  Now we have the strings as whole sentences.
