### ISSUE TITLE
French locale problem

### ISSUE THREAD

**Issue by reff** [sliced-invoices/sliced-invoices#52]
If the language of an account is set to French, Sliced Invoices doesn't work properly because the **due date** is impossible to set. If the language is set back to English, the problem disappears.

**Comment by grantalltodavid** [comment]
Fixed, see ad05bbf1ba7e80bd3f785583aad250ad451c3e23.

Comments: This is not specifically a French problem, but rather a problem from the fact that PHP's strtotime() function cannot understand month names in ANY language other than English.

This issue refers to the quick edit feature, where we had the date in 1 text field, for example "June 16, 2019".  strototime() understand this just fine.  However when translated in French it becomes "Juin 16, 2019", which strtotime cannot understand.  The same would be true for any other non-English language.

As part of this update I've replaced the 1 text field with individual fields for each component of the date, following the same pattern WP now uses for dates on posts.
