### ISSUE TITLE
Send email when adding manual payments

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#8]
(iref 37140)

When adding a payment manually (or manually marking an invoice as paid) no emails are sent. Adding support for sending emails in those situations would help users notify their customers that payment has been applied or the invoice has been paid in full.

**Comment by grantalltodavid** [comment]
This is coming in v3.7.  See https://github.com/sliced-invoices/sliced-invoices/commit/fbafadcb9c30bc7f92470350df39c33175c45a35

**Comment by nutsandbolts** [comment]
Solved via https://github.com/sliced-invoices/sliced-invoices/commit/39e561c05e25955c34a4a84f95e05513a7df6527
